[wiki2035]
base_url=
token=
company_name=

[db]
# supported dialects: https://docs.sqlalchemy.org/en/20/dialects/
dialect=sqlite
host=
port=
username=
password=
dbname=db.sqlite3
extra=

[requests_worker]
timeout=0
max_attempts=3

[uvicorn]
host=127.0.0.1
port=8000
