"""Bind status table

Revision ID: 568488b24477
Revises: fbbc0000d90f
Create Date: 2024-04-18 01:39:46.098225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "568488b24477"
down_revision: Union[str, None] = "fbbc0000d90f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units_bind_status",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "REVIEW",
                "APPROVED",
                "DECLINED",
                "ACCEPTED",
                "TRANSFER",
                "FINISHED",
                "EXPELLED",
                "UNKNOWN",
                name="unitcoursestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["excel_file.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "method"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("units_bind_status")
    # ### end Alembic commands ###
